### ISSUE TITLE
Possible to start from VCF data?

### ISSUE THREAD

**Issue by andreaswallberg** [jkimlab/PAPipe#6]
Dear developers,

Thanks for developing a very useful tool!

I wonder if it possible to start the pipeline with VCF files only, without NGS short read data and processing.

**Comment by nayoung9** [comment]
Dear Andreas, 
Thank you for your kind words and for using our tool! 
Yes, it is possible to start the pipeline using only VCF files without the need for NGS short read data and processing. 
Please ensure that your VCF files are correctly formatted and contain the necessary information for the pipeline to work efficiently. 

You can generate the parameter file within this page with the option "Begin analysis from population genetic analysis":

http://bioinfo.konkuk.ac.kr/PAPipe/parameter_builder/
<img width="926" alt="image" src="https://github.com/user-attachments/assets/0714b70d-cbf2-4e42-9812-927947ff0f7d">

If you encounter any issues or need further assistance, feel free to reach out. 

Best regards, 
Nayoung
